easy_admin:
    entities:
#        - App\Entity\User
        User:
            class: App\Entity\User
        Item:
            class: App\Entity\Item
            list:
                fields: ['id', 'name', 'quality', 'class', 'subClass']
        Category:
            class: App\Entity\Category
            list:
                fields: ['name', 'sorting']
        SubCategory:
            class: App\Entity\SubCategory
            list:
                fields: ['name', 'parentClass', 'sorting']
        Character:
            class: App\Entity\Character
            list:
                fields: ['name', 'spec', 'class']
            form:
                fields:
                    - { property: "name" }
                    - property: "spec"
                      label: 'Spec'
                      type: choice
                      type_options:
                          choices:
                              'Select': 0
                              'Tank': 1
                              'Healer': 2
                              'DPS': 3
                    - property: "class"
                      label: 'Class'
                      type: choice
                      type_options:
                          choices:
                              'Select': 0
                              'Warrior': 1
                              'Priest': 2
                              'Mage': 3
                              'Warlock': 4
                              'Rogue': 5
                              'Druid': 6
                              'Hunter': 7
                              'Shaman': 8
                              'Paladin': 9
