twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    globals:
        layout: '%env(LAYOUT)%'
        siteName: '%env(SITENAME)%'
        footer: '%env(FOOTER)%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@TetranzSelect2Entity/Form/fields.html.twig'
